### ISSUE TITLE
Webserver crashes when started

### ISSUE THREAD

**Issue by folkertdev** [RUGSoftEng/2017-Web-Service-Author-Analysis#1]
I get the following error when I start the node server (after installing dependencies with `npm install` (in the `backend` directory, contrary to what the readme says). 

```
> webserver@1.0.0 start /home/devries/2017-Web-Service-Author-Analysis/backend
> npm run build:live


> webserver@1.0.0 build:live /home/devries/2017-Web-Service-Author-Analysis/backend
> nodemon --exec "node_modules\.bin\ts-node" -- "index.ts"

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node_modules\.bin\ts-node index.ts`
sh: 1: node_modules.bints-node: not found
[nodemon] failed to start process, "node_modules\.bin\ts-node" exec not found
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (127)
    at emit (events.js:144:17)
    at ChildProcess.<anonymous> (/home/devries/2017-Web-Service-Author-Analysis/backend/node_modules/nodemon/lib/monitor/run.js:118:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/devries/.nvm/versions/node/v5.0.0/bin/node" "/home/devries/.nvm/versions/node/v5.0.0/bin/npm" "run" "build:live"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! webserver@1.0.0 build:live: `nodemon --exec "node_modules\.bin\ts-node" -- "index.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webserver@1.0.0 build:live script 'nodemon --exec "node_modules\.bin\ts-node" -- "index.ts"'.
npm ERR! This is most likely a problem with the webserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --exec "node_modules\.bin\ts-node" -- "index.ts"
npm ERR! You can get their info via:
npm ERR!     npm owner ls webserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/devries/2017-Web-Service-Author-Analysis/backend/npm-debug.log

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/devries/.nvm/versions/node/v5.0.0/bin/node" "/home/devries/.nvm/versions/node/v5.0.0/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! webserver@1.0.0 start: `npm run build:live`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webserver@1.0.0 start script 'npm run build:live'.
npm ERR! This is most likely a problem with the webserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:live
npm ERR! You can get their info via:
npm ERR!     npm owner ls webserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/devries/2017-Web-Service-Author-Analysis/backend/npm-debug.log
```

@dennis-school any idea what this might be?

**Comment by dennis-school** [comment]
*nix systems don't recognize the backslash paths of Windows. (And vice-versa)
This is now resolved. Now run:

- `npm run build:windows` for Windows systems.
- `npm run build:linux` for *nix systems.
